name: ServerNetwork
author: TheDarkGRO
api: 
- 3.0.0
- 3.0.1
- 3.1.0
- 3.0.2
- 3.0.3
- 3.0.4
- 3.0.5
- 3.0.6
- 3.0.7
- 3.0.8
- 3.0.9
- 4.0.0
- 4.0.1
- 4.0.2
- 4.0.3
- 4.0.4
- 4.0.5
- 4.0.6
- 4.0.7
- 4.0.8
- 4.0.9
- 5.0.0
version: 1.0.0
main: TheDarkGRO\ServerUI
description: Server Network Settings UI
commands:
  server:
    description: Server Network Control Panel
    usage: /server
  addadmin:
    description: add a Player to Admin Panel
    permission: network.addadmin
    usage: /addadmin
  removeadmin:
    description: remove a Player from Admin Panel
    permission: network.removeadmin
    usage: /removeadmin
  adminlist:
    description: see all Admins . ServerNetwork
    permission: network.adminlist
    usage: /adminlist
    
